### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by WillQi** [wwwg/m.io#3]
Does this github repository still work? It isn't working for me. I'm not sure if it's just me or if moomoo.io's protocol changed.

**Comment by ECMAScript3** [comment]
Moomoo.io‘s protocol has changed several times since this was last updated.

**Comment by wwwg** [comment]
Moomoo.io's protocol has changed very little, but the fact is that I've lost interest in this project and I no longer have interest in contributing to it. I will continue to maintain the project as long as there are people willing to contribute.
